### ISSUE TITLE
could not run dcn in yolov5l_s

### ISSUE THREAD

**Issue by hubery1619** [YEARNLL/dcn-4-heads-yolov5#2]
Hi, when I want to change the Conv to DConv in the 10 layer in yolov5l_s, it shows the error as follows.
Given groups=1, weight of size [512, 512, 1, 1], expected input[1, 1024, 8, 8] to have 512 channels, but got 1024 channels instead. Would you mind giving me some help? Thanks so much.

**Comment by huangzizheng01** [comment]
Hello, sometimes, adding DCN does cause dimension mismatch. This is due to the inflexible modular configuration manner of yolov5. Please calculate the dimension of the module before and after adding DCN and change the configuration file in yaml format and the dimension of 'DConv2' or 'DConv' module in common.py
